// Copyright ChenTaiye 2025. All Rights Reserved.

#include "SaveGameType.h"

DEFINE_LOG_CATEGORY(GenericLogSaveGame);

UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayVersion_SaveGame, "GameplayVersion.SaveGame");

UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame, "GameplayMessage.Channel.SaveGame");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameRegister, "GameplayMessage.Channel.SaveGame.OnSaveGameRegister");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameUnRegister, "GameplayMessage.Channel.SaveGame.OnSaveGameUnRegister");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameRefresh, "GameplayMessage.Channel.SaveGame.OnSaveGameRefresh");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameDirty, "GameplayMessage.Channel.SaveGame.OnSaveGameDirty");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameSaveStart, "GameplayMessage.Channel.SaveGame.OnSaveGameSaveStart");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameSaveFinish, "GameplayMessage.Channel.SaveGame.OnSaveGameSaveFinish");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameLoadStart, "GameplayMessage.Channel.SaveGame.OnSaveGameLoadStart");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameLoadFinish, "GameplayMessage.Channel.SaveGame.OnSaveGameLoadFinish");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnAutoSaveStart, "GameplayMessage.Channel.SaveGame.OnAutoSaveStart");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnAutoSaveFinish, "GameplayMessage.Channel.SaveGame.OnAutoSaveFinish");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnGlobalSaveGameLoadStart, "GameplayMessage.Channel.SaveGame.OnGlobalSaveGameLoadStart");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnGlobalSaveGameLoadOnceFinish, "GameplayMessage.Channel.SaveGame.OnGlobalSaveGameLoadOnceFinish");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnGlobalSaveGameLoadFinish, "GameplayMessage.Channel.SaveGame.OnGlobalSaveGameLoadFinish");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameSlotLoadStart, "GameplayMessage.Channel.SaveGame.OnSaveGameSlotLoadStart");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameSlotLoadOnceFinish, "GameplayMessage.Channel.SaveGame.OnSaveGameSlotLoadOnceFinish");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameSlotLoadFinish, "GameplayMessage.Channel.SaveGame.OnSaveGameSlotLoadFinish");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameSlotEnter, "GameplayMessage.Channel.SaveGame.OnSaveGameSlotEnter");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_SaveGame_OnSaveGameSlotLeave, "GameplayMessage.Channel.SaveGame.OnSaveGameSlotLeave");
