#include "LevelStreamingType.h"

DEFINE_LOG_CATEGORY(GenericLogLevelStreaming);

UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_LevelStreaming, "GameplayMessage.Channel.LevelStreaming");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_LevelStreaming_OnLoadLevelStreamingHandleRegister, "GameplayMessage.Channel.LevelStreaming.OnLoadLevelStreamingHandleRegister");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_LevelStreaming_OnUnLoadLevelStreamingHandleRegister, "GameplayMessage.Channel.LevelStreaming.OnUnLoadLevelStreamingHandleRegister");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_LevelStreaming_OnSetLevelStreamingVisibilityHandleRegister, "GameplayMessage.Channel.LevelStreaming.OnSetLevelStreamingVisibilityHandleRegister");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_LevelStreaming_OnDefaultLevelsLoadStart, "GameplayMessage.Channel.LevelStreaming.OnDefaultLevelsLoadStart");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_LevelStreaming_OnDefaultLevelsLoadOnceFinish, "GameplayMessage.Channel.LevelStreaming.OnDefaultLevelsLoadOnceFinish");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_LevelStreaming_OnDefaultLevelsLoadFinish, "GameplayMessage.Channel.LevelStreaming.OnDefaultLevelsLoadFinish");
