#include "WorldPartitionType.h"

DEFINE_LOG_CATEGORY(GenericLogWorldPartition);

UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_WorldPartition, "GameplayMessage.Channel.WorldPartition");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_WorldPartition_OnLoadWorldPartitionHandleRegister, "GameplayMessage.Channel.WorldPartition.OnLoadWorldPartitionHandleRegister");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_WorldPartition_OnUnLoadWorldPartitionHandleRegister, "GameplayMessage.Channel.WorldPartition.OnUnLoadWorldPartitionHandleRegister");
UE_DEFINE_GAMEPLAY_TAG(TAG_GameplayMessage_Channel_WorldPartition_OnSetWorldPartitionVisibilityHandleRegister, "GameplayMessage.Channel.WorldPartition.OnSetWorldPartitionVisibilityHandleRegister");
